# db connection
spring.datasource.url = jdbc:postgresql://localhost:5432/bookdb
spring.datasource.username = postgres
spring.datasource.password = Quixote425$

#jpa settings
spring.jpa.hibernate.ddl-auto=update

#show sql queries on console
spring.jpa.show-sql=true

#format sql nicely
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL = DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


spring.application.name=demo
